# Replace 'your-github-username' with your actual GitHub handle
github: [Hadi02-gif]

# If you have a Buy Me A Coffee or Ko-fi, you can add them too:
# custom: [https://www.patreon.com/c/MomodouHadiJallow]
